// 获取所有教材列表
export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE';
// 获取单个教材
export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';
// 发布教材
export const PUBLISH_BOOK_REQUEST = 'PUBLISH_BOOK_REQUEST';
export const PUBLISH_BOOK_SUCCESS = 'PUBLISH_BOOK_SUCCESS';
export const PUBLISH_BOOK_FAILURE = 'PUBLISH_BOOK_FAILURE';
// 获取已发布教材
export const GET_PUBLISHED_REQUEST = 'GET_PUBLISHED_REQUEST';
export const GET_PUBLISHED_SUCCESS = 'GET_PUBLISHED_SUCCESS';
export const GET_PUBLISHED_FAILURE = 'GET_PUBLISHED_FAILURE';
// 申请教材
export const APPLY_BOOK_REQUEST = 'APPLY_BOOK_REQUEST';
export const APPLY_BOOK_SUCCESS = 'APPLY_BOOK_SUCCESS';
export const APPLY_BOOK_FAILURE = 'APPLY_BOOK_FAILURE';
// 获取已申请教材
export const GET_APPLIED_BOOK_REQUEST = 'GET_APPLIED_BOOK_REQUEST';
export const GET_APPLIED_BOOK_SUCCESS = 'GET_APPLIED_BOOK_SUCCESS';
export const GET_APPLIED_BOOK_FAILURE = 'GET_APPLIED_BOOK_FAILURE';
// 获取历史记录
export const GET_RECORD_REQUEST = 'GET_RECORD_REQUEST';
export const GET_RECORD_SUCCESS = 'GET_RECORD_SUCCESS';
export const GET_RECORD_FAILURE = 'GET_RECORD_FAILURE';
// 获取已申请人列表
export const GET_APPLIER_LIST_REQUEST = 'GET_APPLIER_LIST_REQUEST';
export const GET_APPLIER_LIST_SUCCESS = 'GET_APPLIER_LIST_SUCCESS';
export const GET_APPLIER_LIST_FAILURE = 'GET_APPLIER_LIST_FAILURE';
// 更改教材状态
export const UPDATE_BOOK_REQUEST = 'UPDATE_BOOK_REQUEST';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';
// 更改申请状态
export const UPDATE_APPLIER_LIST_REQUEST = 'UPDATE_APPLIER_LIST_REQUEST';
export const UPDATE_APPLIER_LIST_SUCCESS = 'UPDATE_APPLIER_LIST_SUCCESS';
export const UPDATE_APPLIER_LIST_FAILURE = 'UPDATE_APPLIER_LIST_FAILURE';
// 创建评价
export const CREATE_EVALUATE_REQUEST = 'CREATE_EVALUATE_REQUEST';
export const CREATE_EVALUATE_SUCCESS = 'CREATE_EVALUATE_SUCCESS';
export const CREATE_EVALUATE_FAILURE = 'CREATE_EVALUATE_FAILURE';
// 获取评价
export const GET_EVALUATE_REQUEST = 'GET_EVALUATE_REQUEST';
export const GET_EVALUATE_SUCCESS = 'GET_EVALUATE_SUCCESS';
export const GET_EVALUATE_FAILURE = 'GET_EVALUATE_FAILURE';
// 直接删除
export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
